name: MasterDeployCI
on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  appName: "splunk-app-for-ethereum"
  releaseName: "Splunk App for Ethereum"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Release
      run: |
          touch ${{env.appName}}.tgz
          tar --transform 's,^\.,${{env.appName}},' --exclude='.git*' --exclude='${{env.appName}}.tgz' -cvzf ${{env.appName}}.tgz ./
   - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: latest
        prerelease: false
        files: |
          splunk-app-for-ethereum.tgz
